### ISSUE TITLE
Installation Method in magento2 wordpress integration

### ISSUE THREAD

**Issue by DRAJI** [bentideswell/magento2-wordpress-integration-yoastseo#1]
Hi,
I have been using Fishpig module for Magento2 & Wordpress integration. I have Integrated it successfully.
Sorry for my question. This Yoast Seo plugin file format look like an magento2 structure. I have installed in magento2 project. How to call this plugin feature in wordpress? Nothing seems to be working...

**Comment by bentideswell** [comment]
@DRAJI, this extension should be installed in Magento 2 in the normal way. You then need to install the Yoast SEO plugin in WordPress. You can download the Yoast SEO plugin from:

https://wordpress.org/plugins/wordpress-seo/

Download the zip file, extract the files and upload the folder to your wp-content/plugins folder. You can then enable the plugin in the WordPress Admin.

**Comment by DRAJI** [comment]
Thank you for your response.

I have tried to install the some of the wordpress plugin. Its working fine as expected in wordpress admin, but in frontend, not working. For those plugins, Need to add any magento file as "Yoast SEO" plugin?

**Comment by robohaus** [comment]
Hi,

Just want to confirm...
1. Create folder .../app/code/FishPig/WordPress_Yoast
2. Upload files from this extension to folder in step 1.
3. Via CLI run
4. magento setup:upgrade
5. magento setup:di:compile
6. magento setup:static-content:deploy
7. Via Magento admin panel, flush cache ?
8. Install Yoast SEO

Is there any impact to installing Yoast SEO before installing this extension?

regards
Michael

**Comment by bentideswell** [comment]
There is no impact from the timing of the installation of the Yoast SEO plugin in WordPress. As soon as the plugin is installed in WordPress, the SEO data should start displaying in Magento.
