### ISSUE TITLE
Canonical instead of Link tags in the header on archive pages

### ISSUE THREAD

**Issue by ghost** [bentideswell/magento2-wordpress-integration-yoastseo#10]
Hi,
I'd like to report an seo issue, on a paginated archive page yoast will give "link" tags in the header with "prev" and "next" links. Search engines then know that the page is part of an archive.
eg..
link rel="prev" href="https://local.wp/sleep-matters/sleep_views/page/2/"
link rel="next" href="https://local.wp/sleep-matters/sleep_views/page/4/"

Fishpig is currently not putting these into the header and is instead putting a "canonical" link there instead which links back to the first page of the archive.
eg.. 
link  rel="canonical" href="https://local.wp/sleep-matters/sleep_views/"

This is causing confusion with search engines and we would appreciate it if you could look at this issue.

**Comment by ghost** [comment]
Ill close this issue as google have decided to retire rel="prev" and rel="next".

**Comment by jsterling** [comment]
There may be cause to re-open this; the default behaviour is to canonical back to first page, whereas Yoast behaviour (https://kb.yoast.com/kb/canonical-urls-in-wordpress-seo/#archives) is that canonical links should be paginated.

**Comment by bentideswell** [comment]
The fix for canonical's is part of [FishPig_WordPress](https://fishpig.co.uk/magento/wordpress-integration/). I have just released an update that fixes this.
