### ISSUE TITLE
Notice: Undefined property: FishPig\\WordPress_Yoast\\Model\\StringRewriter::$yoastHelper in /magento2-wordpress-integration-yoastseo\/Model\/StringRewriter.php on line 130

### ISSUE THREAD

**Issue by sebastian-enz** [bentideswell/magento2-wordpress-integration-yoastseo#11]
Hello,

after upgrading all your WP plugins we get this error.

Checking your code base, there is no reference anywhere to declare yoastHelper

Is it a bug, or am I doing something wrong?

Thank you very much!

**Comment by bentideswell** [comment]
Thanks for the bug. I can confirm this and I have released an update that fixes it.
