### ISSUE TITLE
Module breaks on Magento 2.2.0 because of underscore in class naming

### ISSUE THREAD

**Issue by fuunnx** [bentideswell/magento2-wordpress-integration-yoastseo#3]
Hi, I have this exception on a fresh installation of Magento CE 2.2.0 when I enable the plugin. It did not appear on previous versions (2.1.x).

```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'FishPig\WordPress_Yoast\Block\OpenGraph' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 705

Element 'block', attribute 'class': 'FishPig\WordPress_Yoast\Block\OpenGraph' is not a valid value of the atomic type 'blockClassType'.
Line: 705
```

**Comment by fuunnx** [comment]
Finding and replacing every `WordPress_Yoast` to `WordPressYoast ` in the module fixed the problem.

**Comment by bentideswell** [comment]
Have you installed the module in app/code/FishPig/WordPress_Yoast or pp/code/FishPig/WordPressYoast?

**Comment by fuunnx** [comment]
It was installed in `app/code/FishPig/WordPress_Yoast`.

(For my fix I moved it to `app/code/FishPig/WordPressYoast` just in case)

**Comment by bentideswell** [comment]
Unfortunately that isn't a fix that I can apply to the module. I will try and recreate the issue and find a fix.

**Comment by fuunnx** [comment]
Ok, tell me if you need more informations

**Comment by leek** [comment]
Receiving this same error on a recent 2.2.1 installation.

**Comment by bentideswell** [comment]
I have submitted a pull request for this issue and it has been accepted and merged by Magento. I'm not sure when it will be available in the released and stable code but you can find [more information here](https://github.com/magento/magento2/pull/11765).

[This link](https://github.com/magento/magento2/pull/11765/files) will show you the 2 single character changes you can make to resolve it in your installation. This involves editing a core file, however as it has been accepted by Magento and merged, this change will be made in one of the next releases, so there is no harm in you making the change now.

After making the change you must flush the cache to see the results.
