### ISSUE TITLE
can't install on magento 2 install?

### ISSUE THREAD

**Issue by kennyeliason** [bentideswell/magento2-wordpress-integration-yoastseo#4]
Hey Ben, getting this error when installing this module:
<img width="731" alt="screen shot 2018-02-20 at 11 52 55 pm" src="https://user-images.githubusercontent.com/5042392/36468681-35f3be9c-1699-11e8-8df8-5194e731123b.png">

`composer require fishpig/magento2-wordpress-integration-yoastseo:dev-master
./composer.json has been updated                                                Loading composer repositories with package information
Updating dependencies (including require-dev)                                   Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fishpig/magento2-wordpress-integration-yoastseo dev-master requires magento/product-community-edition ^2.0.0 -> no matching package found.
    - fishpig/magento2-wordpress-integration-yoastseo dev-master requires magento/product-community-edition ^2.0.0 -> no matching package found.
    - Installation request for fishpig/magento2-wordpress-integration-yoastseo dev-master -> satisfiable by fishpig/magento2-wordpress-integration-yoastseo[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.`

After confirming everything else, it has to do with the requirement of magento/product-community-edition ^2.0.0. I'm on version 2.2. 

<img width="1427" alt="screen shot 2018-02-20 at 11 57 07 pm" src="https://user-images.githubusercontent.com/5042392/36468819-caeefc3c-1699-11e8-88da-49e350d6b666.png">

Will it not work with 2.2? Seems like it should?

**Comment by bentideswell** [comment]
Hi Kenny,

All looks good to me. Quite a few people use Composer to install it and I haven't had any reports of any issues, on Magento 2.2 and 2.3. Could it be a local issue? Do you have another site you could try it on?

**Comment by kennyeliason** [comment]
Solved by installing manually, couldn't find these instructions anywhere else... might help someone else:

1. Download from Github as a zip file.
2. extract zip file
3. rename folder to WordPress_Yoast
4. upload to /app/code/FishPig/
5. run: php bin/magento module:enable FishPig_WordPress_Yoast
6. run: php bin/magento setup:upgrade
7. run: php bin/magento setup:di:compile

Hope that helps someone else!

**Comment by bentideswell** [comment]
Thanks for posting this Kenny. I will look into on my end and see if I can find anything could cause the issue.
