### ISSUE TITLE
Magento 2.1 incompatibility?

### ISSUE THREAD

**Issue by planart** [bentideswell/magento2-wordpress-integration-yoastseo#5]
Hello bentideswell.
Installed the module in app/code/FishPig/WordPress_Yoast
then I've tried to compile but I've received a strange error that break magento
The steps to reproduce error are here, Any idea to help working the integration?

# php bin/magento module:enable FishPig_WordPress_Yoast
--> The following modules have been enabled:
- FishPig_WordPress_Yoast

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them. <--

# php bin/magento setup:di:compile
--> Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 70.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 1 sec 76.2 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 76Repositories code generation... 2/7 [========>-------------------]  28% 34 secs Service data attributes generation... 2/7 [========>-------------------]  28% 34Service data attributes generation... 3/7 [============>---------------]  42% 34Application code generator... 3/7 [============>---------------]  42% 34 secs 30Application code generator... 4/7 [================>-----------]  57% 2 mins 330Interceptors generation... 4/7 [================>-----------]  57% 2 mins 330.8 Interceptors generation... 5/7 [====================>-------]  71% 3 mins 379.2 Area configuration aggregation... 5/7 [====================>-------]  71% 3 minsArea configuration aggregation... 6/7 [========================>---]  85% 4 minsInterception cache generation... 6/7 [========================>---]  85% 4 mins Interception cache generation... 7/7 [============================] 100% 5 mins Interception cache generation... 7/7 [============================] 100% 5 mins 408.2 MiB
Generated code and dependency injection configuration successfully. <--

# php bin/magento setup:upgrade
-->                                                                         
  [Exception]                                                                  
  Warning: file_get_contents(/var/www/pathtomagento/var/di/setup.ser): fa 
  iled to open stream: No such file or directory in /var/www/pathtomagento  
  /vendor/magento/framework/App/ObjectManager/ConfigLoader/Compiled  
  .php on line 28                                       
                                                                               
setup:upgrade [--keep-generated] [--magento-init-params="..."] <--

**Comment by bentideswell** [comment]
Hi @planart, why are you compiling before upgrading? Does it work when you reverse this and run:

    php bin/magento module:enable FishPig_WordPress_Yoast
    php bin/magento setup:upgrade
    php bin/magento setup:di:compile

**Comment by planart** [comment]
Hi bentideswell. Thanks for your immediate reply and sorry for the inverted Compile after Upgrade. 
I have solved the upgrade error with this;
- php bin/magento module:disable FishPig_WordPress_Yoast = OK
- php bin/magento setup:upgrade = OK
- php bin/magento setup:di:compile = OK
and rerun enable, upgrade and compile.
OK
Now I see some unexpected result.
The modules are active (seeing it in the compile list as Module 'FishPig_WordPress' and Module 'FishPig_WordPress_Yoast'), but Yoast in Wordpress generate this error:
« Fatal error: Uncaught exception 'RuntimeException' with message 'Source class "\WPSEO_Role_Manager_" for "WPSEO_Role_Manager_Factory" generation does not exist.' in /var/www/pathtomagento/vendor/magento/framework/Code/Generator.php:185 Stack trace: #0 /var/www/pathtomagento/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('WPSEO_Role_Mana...', Object(Magento\Framework\ObjectManager\Code\Generator\Factory)) #1 /var/www/pathtomagento/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('WPSEO_Role_Mana...') #2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('WPSEO_Role_Mana...') #3 /var/www/pathtomagento/wp/wp-content/plugins/wordpress-seo/admin/roles/class-register-roles.php(27): spl_autoload_call('WPSEO_Role_Mana...') #4 [internal function]: WPSEO_Register_Roles->register('') #5 /var/www/pathtom [this strange cut here] in /var/www/pathtomagento/vendor/magento/framework/Code/Generator.php on line 185 »
Have some other trick I can try?

**Comment by planart** [comment]
PS I don't see any setting about fishpig yoast in magento administration, but there is an option to activate or deactivate output for this module in config advanced

**Comment by bentideswell** [comment]
Do you have a plugin installed in WordPress that integrates with Magento? It is this causing your issue. Disable and delete this plugin and all should work.

**Comment by planart** [comment]
Yes, is a plugin, very thanks
