### ISSUE TITLE
[Question] Does this still work with Yoast?

### ISSUE THREAD

**Issue by OwenMelbz** [bentideswell/magento2-wordpress-integration-yoastseo#7]
Hi,

We've recently installed Yoast into our WordPress install - however the page title and description are not pulling out what is configured in WordPress.

I've tried debugging within `module-wordpress/Helper/View.php` inside the `applyPageConfigData` method which does:

```php
var_dump($entity->getPageTitle());
```

However this returns the original page title rather than the Yoast version.

--

Is there something else we need to do to be able to pull custom page titles/meta description?

Many thanks

**Comment by OwenMelbz** [comment]
Update: Upon further investigation i found this code

```php

	/**
	 *
	**/
	public function getName()
	{
		return $this->_getData('post_title');
	}

	/**
	 *
	**/
	public function getMetaDescription()
	{
		return $this->getExcerpt(20);
	}
```

Would this suggest the latest version of your plugin does not support Yoast?

Many thanks

**Comment by bentideswell** [comment]
Yes Yoast is supported. The code is what runs without Yoast. Yoast then uses plugins to modify those methods. You need the latest version of both modules.

**Comment by OwenMelbz** [comment]
Ah I think I've found the confusion here, The Fishpig website says

![magento_wordpress_integration](https://user-images.githubusercontent.com/1094740/46800158-bb667f80-cd4e-11e8-82e6-e76f35c91ee0.png)

Did not realise until I looked at this github url that there is in fact a extra addon which is needed!

I will see if this solves the issue ha
