### ISSUE TITLE
Invalid block type: FishPig\WordPress_Yoast\Block\OpenGraph

### ISSUE THREAD

**Issue by shachiarkatkar** [bentideswell/magento2-wordpress-integration-yoastseo#8]
Hi got this error when i opened blog link
Invalid block type: FishPig\WordPress_Yoast\Block\OpenGraph

**Comment by bentideswell** [comment]
What version of Magento are you using? In Magento 2.2 and below, there was an issue that stops modules with underscores in their name from using a custom layout file. [This pull request](https://github.com/magento/magento2/pull/11765) fixes it.

You can manually apply this fix (it's a small change in 1 file) by making the change [here](https://github.com/magento/magento2/pull/11765/files).
